src/Enigmatic/CRMBundle/Form/ActivityType.php
<?php

namespace Enigmatic\CRMBundle\Form;

use Doctrine\ORM\EntityRepository;
use Enigmatic\CRMBundle\Entity\Activity;
use Enigmatic\CRMBundle\Manager\ActivityTypeManager;
use Enigmatic\CRMBundle\Manager\UserManager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Security\Core\Authorization\AuthorizationChecker;
use Symfony\Component\Translation\Translator;

class ActivityType extends AbstractType
{
    protected $authorizationChecker;
    protected $userManager;
    protected $activityTypeManager;
    protected $translator;

    /**
     * @param AuthorizationChecker $authorizationChecker
     */
    public function __construct(AuthorizationChecker $authorizationChecker, UserManager $userManager, ActivityTypeManager $activityTypeManager, Translator $translator)
    {
        $this->authorizationChecker = $authorizationChecker;
        $this->userManager = $userManager;
        $this->activityTypeManager = $activityTypeManager;
        $this->translator = $translator;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) use ($builder) {

            $event->getForm()
                ->add('dateStart', 'datetime', array (
                    'label'         => (!(!$event->getData()->getId() && $event->getData()->getReplannedBy()))?'enigmatic.crm.activity.form.field.dateStart.label':'enigmatic.crm.activity.form.field.dateStart.replann.label',
                    'widget'        => 'single_text',
                    'input'         => 'datetime',
                    'format'        => 'dd-MM-yyyy H:m',
                    'required'      => true,
                    'attr'          => array(
                        'class'     => 'datetimepicker',
                        'placeholder'     => 'dd-mm-yyyy h:m',
                    )
                ));


            if (!(!$event->getData()->getId() && $event->getData()->getReplannedBy())) {
                $event->getForm()
                    ->add('type', 'genemu_jqueryselect2_entity', array(
                        'class' => 'EnigmaticCRMBundle:ActivityType',
                        'multiple' => false,
                        'expanded' => false,
                        'label' => 'enigmatic.crm.activity.form.field.type.label',
                        'empty_value' => 'enigmatic.crm.activity.form.field.type.empty_value',
                        'choices'  => $this->getArrayOfEntities(),
                        'required' => true
                    ))
                    ->add('comment', 'textarea', array (
                        'label'         => 'enigmatic.crm.activity.form.field.comment.label',
                        'required'      => false,
                    ));
            }

            if (!$event->getData()->getAccount() || $event->getData()->getId()) {
                $event->getForm()->add('account', 'genemu_jqueryselect2_entity', array(
                    'class' => 'EnigmaticCRMBundle:Account',
                    'multiple' => false,
                    'expanded' => false,
                    'label' => 'enigmatic.crm.activity.form.field.account.label',
                    'empty_value' => 'enigmatic.crm.activity.form.field.account.empty_value',
                    'required' => true,
                    'query_builder' => function (EntityRepository $er) use ($event) {
                        $params = array();
                        if ($this->authorizationChecker->isGranted('ROLE_RCA') && !$this->authorizationChecker->isGranted('ROLE_RS'))
                            $params['search']['agency'] = ($this->userManager->getCurrent()?$this->userManager->getCurrent()->getAgency():null);
                        elseif ($this->authorizationChecker->isGranted('ROLE_CA') && !$this->authorizationChecker->isGranted('ROLE_RS')) {
                            $params['search']['agency'] = ($this->userManager->getCurrent()?$this->userManager->getCurrent()->getAgency():null);
                            $params['search']['account_owner'] = $this->userManager->getCurrent();
                        }

                        return $er->getER($params);
                    },
                ));
            }

            if ($event->getData()->getId()) {
                $event->getForm()->add('dateEnd', 'datetime', array (
                    'label'         => 'enigmatic.crm.activity.form.field.dateEnd.label',
                    'widget'        => 'single_text',
                    'input'         => 'datetime',
                    'format'        => 'dd-MM-yyyy H:m',
                    'required'      => true,
                    'attr'          => array(
                        'class'     => 'datetimepicker',
                        'placeholder'     => 'dd-mm-yyyy h:m',
                    )
                ));
            }

            if (!$event->getData()->getUser()) {
                $event->getForm()->add('user', 'genemu_jqueryselect2_entity', array(
                    'class' => 'EnigmaticCRMBundle:User',
                    'multiple' => false,
                    'expanded' => false,
                    'label' => 'enigmatic.crm.activity.form.field.user.label',
                    'empty_value' => 'enigmatic.crm.activity.form.field.user.empty_value',
                    'required' => true
                ));
            }
        });

        $builder->addEventListener(
            FormEvents::SUBMIT,
            function (FormEvent $event) use($options) {
                if (!$event->getData()->getId()) {
                    $date = clone $event->getData()->getDateStart();
                    $event->getData()->setDateEnd($date->modify('+30 min'));
                }
            }
        );
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Enigmatic\CRMBundle\Entity\Activity'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'enigmatic_crm_activity';
    }

    protected function getArrayOfEntities() {
        $activities = $this->activityTypeManager->getAll();
        $list = array();
        foreach($activities as $activity){
            $list[$this->translator->trans('enigmatic.crm.activity_type.field.type.'.$activity->getType())][] = $activity;
        }
        return $list;
    }
}

src/Enigmatic/CRMBundle/Controller/CampaignFaxingController.php
<?php

namespace Enigmatic\CRMBundle\Controller;

use Enigmatic\CRMBundle\Entity\CampaignFaxing;
use Enigmatic\CRMBundle\Entity\CampaignFaxingFax;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class CampaignFaxingController extends Controller
{
    /**
     * @Secure(roles={"ROLE_CA"})
     */
    public function listAction()
    {
        if (!$this->container->getParameter('enigmatic_crm.ecofax.login') || !$this->container->getParameter('enigmatic_crm.ecofax.password'))
            $this->get('session')->getFlashBag()->add('warning', $this->get('translator')->trans('enigmatic.crm.campaign_faxing.errors.config_ecofax'));

        $params = $this->get('enigmatic_crm.service.list')->parseRequest($this->get('request')->request->all());

        if ($this->get('security.authorization_checker')->isGranted('ROLE_RCA') && !$this->get('security.authorization_checker')->isGranted('ROLE_RS'))
            $params['search']['agency'] = ($this->get('enigmatic_crm.manager.user')->getCurrent()?$this->get('enigmatic_crm.manager.user')->getCurrent()->getAgency():null);
        elseif ($this->get('security.authorization_checker')->isGranted('ROLE_CA') && !$this->get('security.authorization_checker')->isGranted('ROLE_RS')) {
            $params['search']['createdBy'] = $this->get('enigmatic_crm.manager.user')->getCurrent();
        }

        $campaigns = $this->get('enigmatic_crm.manager.campaign_faxing')->getList($params['page'], $params['limit'], $params);
        $params['entity'] = 'CampaignFaxing';
        $params['total'] = $campaigns->count();

        return $this->get('enigmatic.render')->render($this->renderView('EnigmaticCRMBundle:CampaignFaxing:list.html.twig', array(
            'campaigns'     => $campaigns,
            'params'        => $params
        )));
    }

    /**
     * @Secure(roles={"ROLE_CA"})
     */
    public function viewAction(CampaignFaxing $campaign)
    {
        if (!$this->get('enigmatic_crm.service.grant')->grantCampaignFaxing($campaign))
            throw new AccessDeniedException();

        return $this->get('enigmatic.render')->render($this->renderView('EnigmaticCRMBundle:CampaignFaxing:view.html.twig', array(
            'campaign'       => $campaign
        )));
    }

    /**
     * @Secure(roles={"ROLE_CA"})
     */
    public function addAction()
    {
        $campaign = $this->get('enigmatic_crm.manager.campaign_faxing')->create($this->get('enigmatic_crm.manager.user')->getCurrent());
        $form = $this->createForm('enigmatic_crm_campaign_faxing', $campaign);

        $form->handleRequest($this->get('request'));
        if ($form->isSubmitted() && $form->isValid()) {
            $this->get('enigmatic_crm.manager.campaign_faxing')->save($campaign);
            $this->get('session')->getFlashBag()->add('success', $this->get('translator')->trans('enigmatic.crm.campaign_faxing.message.add'));
            return $this->redirect($this->generateUrl('enigmatic_crm_campaign_faxing_view', array('campaign'=> $campaign->getId())));
        }

        return $this->get('enigmatic.render')->render($this->renderView('EnigmaticCRMBundle:CampaignFaxing:form.html.twig', array(
            'campaign'   => $campaign,
            'form'       => $form->createView()
        )));
    }

    /**
     * @Secure(roles={"ROLE_CA"})
     */
    public function updateAction(CampaignFaxing $campaign)
    {
        if (!$this->get('enigmatic_crm.service.grant')->grantCampaignFaxing($campaign))
            throw new AccessDeniedException();
        if ($campaign->getState() == CampaignFaxing::CAMPAIGN_FAXING_SENDED)
            return $this->redirect($this->generateUrl('enigmatic_crm_campaign_faxing_list'));

        $form = $this->createForm('enigmatic_crm_campaign_faxing', $campaign);

        $form->handleRequest($this->get('request'));
        if ($form->isSubmitted() && $form->isValid()) {
            $this->get('enigmatic_crm.manager.campaign_faxing')->save($campaign);
            $this->get('session')->getFlashBag()->add('success', $this->get('translator')->trans('enigmatic.crm.campaign_faxing.message.update'));
            return $this->redirect($this->generateUrl('enigmatic_crm_campaign_faxing_view', array('campaign'=> $campaign->getId())));
        }

        return $this->get('enigmatic.render')->render($this->renderView('EnigmaticCRMBundle:CampaignFaxing:form.html.twig', array(
            'campaign'   => $campaign,
            'form'       => $form->createView()
        )));
    }

    /**
     * @Secure(roles={"ROLE_CA"})
     */
    public function sendTestAction(CampaignFaxing $campaign)
    {
        $form = $this->createForm('enigmatic_crm_campaign_faxing_test', array('phone' => null));

        $form->handleRequest($this->get('request'));
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            $num_fax = $data['phone'];
            if (strlen($num_fax) == 12)
                $num_fax = '00'.substr($num_fax, 1, 12);
            else
                $num_fax = '0033'.substr($num_fax, 1, 10);

            $mail = $this->get('enigmatic_mailer');

            $i = 1;
            foreach ($campaign->getFaxs() as $fax) {
                $mail->addAttach($fax->getAbsolutePath(), 'fax' . $i . '.pdf');
                $i++;
            }

            $mail->sendMail(($num_fax . '@ecofax.fr')/*'rp@enigmatic.fr'*/, $this->renderView('EnigmaticCRMBundle:CampaignFaxing/Email:faxing.html.twig', array(
                'subject' => $this->container->getParameter('enigmatic_crm.ecofax.login'),
                'content' => $this->container->getParameter('enigmatic_crm.ecofax.password'))
            ));

            $this->get('session')->getFlashBag()->add('success', $this->get('translator')->trans('enigmatic.crm.campaign_faxing.message.send_test'));
            return $this->redirect($this->generateUrl('enigmatic_crm_campaign_faxing_view', array('campaign'=> $campaign->getId())));
        }

        return $this->get('enigmatic.render')->render($this->renderView('EnigmaticCRMBundle:CampaignFaxing:sendTest.html.twig', array(
            'campaign'   => $campaign,
            'form'       => $form->createView()
        )));
    }

    /**
     * @Secure(roles={"ROLE_RCA"})
     */
    public function removeAction(CampaignFaxing $campaign)
    {
        if (!$this->get('enigmatic_crm.service.grant')->grantCampaignFaxing($campaign))
            throw new AccessDeniedException();

        $this->get('enigmatic_crm.manager.campaign_faxing')->remove($campaign);

        $this->get('session')->getFlashBag()->add('success', $this->get('translator')->trans('enigmatic.crm.campaign_faxing.message.remove'));
        return $this->redirect($this->generateUrl('enigmatic_crm_campaign_faxing_list'));
    }

    /**
     * @Secure(roles={"ROLE_CA"})
     */
    public function downloadAction(CampaignFaxingFax $fax)
    {
        if (!$this->get('enigmatic_crm.service.grant')->grantCampaignFaxing($fax->getCampaign()))
            throw new AccessDeniedException();

        $fichier = $fax->getAbsolutePath();
        $filename = 'fax.'.substr(strrchr($fichier,'.'), 1);

        return new Response(file_get_contents($fichier), 200, array(
            'Content-Type' => 'application/force-download',
            'Content-disposition' => 'filename='.$filename
        ));
    }
}

src/Enigmatic/CRMBundle/Resources/views/CampaignFaxing/form.html.twig
{% extends app.request.isXmlHttpRequest()?"AppBundle::empty.html.twig":'EnigmaticCRMBundle::layout.html.twig' %}

{% block title %}{% if campaign.getId() %}{% trans %}enigmatic.crm.header.titles.campaign_faxing_update{% endtrans %}{% else %}{% trans %}enigmatic.crm.header.titles.campaign_faxing_add{% endtrans %}{% endif %} - {{ parent() }}{% endblock %}
{% block nav_active %}campaign_faxing{% endblock %}

{% block content %}

    {% import "AppBundle:macro:button.html.twig" as button %}
	
    <div class="action action_left">
        {{ button.create('back', 'Back'|trans, campaign.getId()?path('enigmatic_crm_campaign_faxing_view', {'campaign': campaign.getId()}):path('enigmatic_crm_campaign_faxing_list'), null, 'speednav') }}
    </div>

    <h1>{% if campaign.getId() %}{% trans %}enigmatic.crm.header.titles.campaign_faxing_update{% endtrans %}{% else %}{% trans %}enigmatic.crm.header.titles.campaign_faxing_add{% endtrans %}{% endif %}</h1>

    <form id="campaign_form" method="post" action="" {{ form_enctype(form) }}>


        {{ form_row(form.name) }}

        {#{{ form_row(form.emailSubject) }}#}
        {#{{ form_row(form.emailBody) }}#}

        {{ form_row(form.dateSended) }}
        {{ form_row(form.state) }}

        {% if form.owner is defined %}
            {{ form_row(form.owner) }}
        {% endif %}

        <div id="campaign_contact" style="display:none;">
            {{ form_widget(form.contacts) }}
        </div>

        {{ form_rest(form) }}

    </form>

    <div id="campaign_contact_search">

        <div class="search">
            <form id="campaign_contact_search_form" onsubmit="return Contact.load(false);" >
                <h4>{% trans %}enigmatic.crm.campaign_faxing.form.contacts.title{% endtrans %}</h4>
                <input onkeyup="jQuery('#campaign_contact_search_form').submit();" type="text" id="contacts_availables_search_account_name" value="" placeholder="{% trans %}enigmatic.crm.campaign_faxing.form.contacts.search.account_name.placeholder{% endtrans %}" />
                <input onkeyup="jQuery('#campaign_contact_search_form').submit();" type="text" id="contacts_availables_search_contact_name" value="" placeholder="{% trans %}enigmatic.crm.campaign_faxing.form.contacts.search.name.placeholder{% endtrans %}" />
                <input onkeyup="jQuery('#campaign_contact_search_form').submit();" type="text" id="contacts_availables_search_city" value="" placeholder="{% trans %}enigmatic.crm.campaign_faxing.form.contacts.search.city.placeholder{% endtrans %}" />
            </form>
        </div>

        <div id="list_contacts_availables" class="list_contact">
            <form onsubmit="return false;">
                <h4>{% trans %}enigmatic.crm.campaign_faxing.form.contacts.available.title{% endtrans %}</h4>
                <input class="checkbox_all" type="checkbox" onclick="Contact.checkedAll($(this));" data-type="availables" />
                <em>{% trans %}enigmatic.crm.campaign_faxing.form.contacts.available.description{% endtrans %}</em>
                <div class="list"></div>
            </form>
        </div>
        <a id="list_contacts_action" class="list_contact_action" onclick="Contact.syncCheckbox();">
        </a>
        <div id="list_contacts_enables" class="list_contact">
            <form onsubmit="return false;">
                <h4>{% trans %}enigmatic.crm.campaign_faxing.form.contacts.enabled.title{% endtrans %}</h4>
                <input class="checkbox_all" type="checkbox" onclick="Contact.checkedAll($(this));" data-type="enables" />
                <em>{% trans %}enigmatic.crm.campaign_faxing.form.contacts.enabled.description{% endtrans %}</em>
                <div class="list"></div>
            </form>
        </div>
    </div>
    <script type="text/javascript">
        var Contact = {
            line_id : 0,
            tab_enabled: [],

            reel_contact: null,

            search_contact_name: null,
            search_account_name: null,
            search_city: null,

            init: function(reel_contact_id) {
                this.load(true);
                this.reel_contact = reel_contact_id;
            },

            initEnabled: function() {
                jQuery('#campaign_contact input').each(function() {
                    if (jQuery(this).attr('checked') == 'checked')
                        Contact.add(jQuery('#contact_item_'+jQuery(this).val()));
                });
            },

            parseSearch: function() {
                this.search_contact_name = jQuery('#contacts_availables_search_contact_name').val();
                this.search_account_name = jQuery('#contacts_availables_search_account_name').val();
                this.search_city = jQuery('#contacts_availables_search_city').val();
            },

            load: function (init) {

                this.parseSearch();

                jQuery.ajax({
                    type: "POST",
                    url: '{{ path('enigmatic_crm_contact_search') }}',
                    dataType: "json",
                    data: {contact_name: this.search_contact_name, account_name: this.search_account_name, city: this.search_city, hasFax:1},
                    cache: true,
                    success: function (code_html, statut) {
                        if (code_html.success) {
                            Contact.displayData(code_html.result);
                            if (init)
                                Contact.initEnabled();
                        }
                    },

                    error: function (resultat, statut, erreur) {
                        alert('{% trans %}enigmatic.crm.campaign_faxing.errors.load{% endtrans %}');
                    }
                });

                return false;
            },

            displayData: function (data) {
                jQuery('#list_contacts_availables .list').html('');
                jQuery.each(data, function(i, item) {
                    var add = true;
                    try {if (Contact.tab_enabled[data[i]['id']] === true) add = false;} catch(err) {}
                    if (add)
                        jQuery('#list_contacts_availables .list').append('<div class="contact_block" id="contact_item_'+data[i]['id']+'"><input type="checkbox" name="availables" ><div onclick="Contact.add($(this).parent());" class="contact_item" data-id="'+data[i]['id']+'">'+data[i]['account']+' ('+data[i]['firstname']+' '+data[i]['name']+') <br/><em>'+data[i]['fax']+'</em></div></div>');
                });
            },

            add: function (data) {
                data.fadeOut(500, function() {
                    Contact.enable(data.children('.contact_item').attr('data-id'), data.children('.contact_item').html());
                    data.remove();
                    jQuery('#contact_item_'+data.children('.contact_item').attr('data-id')).fadeOut(0, function() {
                        jQuery(this).fadeIn(500);
                    });
                });
            },

            remove: function (data) {
                data.fadeOut(500, function() {
                    Contact.disable(data.children('.contact_item').attr('data-id'), data.children('.contact_item').html());
                    data.remove();
                    jQuery('#contact_item_'+data.children('.contact_item').attr('data-id')).fadeOut(0, function() {
                        jQuery(this).fadeIn(500);
                    });
                });
            },

            enable: function (id, name) {
                this.placeItem(jQuery('#list_contacts_enables .list'), name, '<div class="contact_block" id="contact_item_'+id+'"><input type="checkbox" name="enables"><div onclick="Contact.remove($(this).parent());" class="contact_item" data-id="'+id+'">'+name+'</div></div>');
                jQuery('#'+this.reel_contact+id).prop('checked', true);
//                jQuery('#list_contacts').append('<input type="hidden" id="line_contact_'+id+'" name="enigmatic_oro_faxingbundle_campaign[contacts]['+this.line_id+'][contact]" value="'+id+'" />');
                this.line_id ++;
                this.tab_enabled[id] = true;
            },

            disable: function (id, name) {
                this.placeItem(jQuery('#list_contacts_availables .list'), name, '<div class="contact_block" id="contact_item_'+id+'"><input type="checkbox" name="availables"><div onclick="Contact.add($(this).parent());" id="contact_item_'+id+'" class="contact_item" data-id="'+id+'">'+name+'</div></div>');
//                jQuery('#line_contact_'+id).remove();
                jQuery('#'+this.reel_contact+id).prop('checked', false);
                this.tab_enabled[id] = false;
            },

            placeItem: function(container, name, html) {
                var place = false;
                container.find('.contact_block').each(function() {
                    if (jQuery(this).children('.contact_item').html() > name && place === false) {
                        jQuery(this).before(html);
                        place = true;
                    }
                });
                if (!place)
                    container.append(html);
            },

            checkedAll: function(box) {
                var container = jQuery('#list_contacts_enables');
                if (box.attr('data-type') == 'availables')
                    container = jQuery('#list_contacts_availables');

                container.find('input').each(function() {
                    if (box.is(':checked') === true)
                        jQuery(this).prop('checked', true);
                    else
                        jQuery(this).prop('checked', false);
                });
            },

            syncCheckbox: function(box) {
                var container = jQuery('#list_contacts_enables');
                container.find('input').each(function() {
                    if (jQuery(this).is(':checked') === true && jQuery(this).hasClass('checkbox_all') === false)
                        Contact.remove(jQuery(this).parent());
                });
                container = jQuery('#list_contacts_availables');
                container.find('input').each(function() {
                    if (jQuery(this).is(':checked') === true && jQuery(this).hasClass('checkbox_all') === false)
                        Contact.add(jQuery(this).parent());
                });
                jQuery('.checkbox_all').each(function() {
                    jQuery(this).attr('checked', false);
                });

            }
        };

        document.ready = function(){
            Contact.init('enigmatic_crm_campaign_faxing_contacts_');
        };

        try {Contact.init('enigmatic_crm_campaign_faxing_contacts_');}catch(err) {}

    </script>

    {{ button.create('submit', campaign.getId()?'enigmatic.crm.campaign_faxing.form.submit.update'|trans:'enigmatic.crm.campaign_faxing.form.submit.add'|trans, null, 'jQuery(\'#campaign_form\').submit();;') }}

{% endblock %}

src/Enigmatic/CRMBundle/Resources/views/CampaignFaxing/sendTest.html.twig
{% extends app.request.isXmlHttpRequest()?"AppBundle::empty.html.twig":'EnigmaticCRMBundle::layout.html.twig' %}

{% block title %}{% trans %}enigmatic.crm.header.titles.campaign_faxing_send_test{% endtrans %} - {{ parent() }}{% endblock %}
{% block nav_active %}campaign_faxing{% endblock %}

{% block content %}

    {% import "AppBundle:macro:button.html.twig" as button %}

    <h1>{% trans %}enigmatic.crm.header.titles.campaign_faxing_send_test{% endtrans %}</h1>

    <div class="action action_left">
        {{ button.create('back', 'Back'|trans, path('enigmatic_crm_campaign_faxing_view', {'campaign': campaign.getId()}), null, 'speednav') }}
    </div>

    <form id="fax_test" class="speednav view" method="post" action="" {{ form_enctype(form) }}>

        {{ form_widget(form) }}

        <input class="btn" type="submit" value="{% trans %}enigmatic.crm.campaign_faxing.form.submit.send_test{% endtrans %}">
        {{ button.create('cancel', 'Cancel'|trans, path('enigmatic_crm_campaign_faxing_view', {'campaign': campaign.getId}), null, 'speednav' ) }}

    </form>

{% endblock %}